apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-

commonLabels:
  environment: production

resources:
  - ../../base

patches:
- path: deployment-patch.yaml
  target:
    name: demo

