apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    environment: baes
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: nginx
        command: ["/bin/bash"]
        args: ["-c", "echo ${HOSTNAME} > /usr/share/nginx/html/index.html"]
        ports:
        - containerPort: 80