apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: nginx
  rules:
  - host: base.dashboard.com
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: stable-service
            port: 
              number: 80
        path: /