apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app: demo

# configurations:
#   - https://argoproj.github.io/argo-rollouts/features

resources:
  - deployment.yaml
  - service-active.yaml
  - service-preview.yaml
  - ingress.yaml
