apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
nameSuffix: "-0.0.1"


resources:
- ../../base

replicas:
- count: 2
  name: demo

patches:
- path: deployment-patch.yaml
  target:
    name: demo
labels:
- includeSelectors: true
  pairs:
    environment: dev
