apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
nameSuffix: "-v001"


resources:
- ../../base

replicas:
- count: 2
  name: demo

patches:
- target:
    kind: Ingress
    name: demo
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.dashboard.com
- path: deployment-patch.yaml
  target:
    name: demo
labels:
- includeSelectors: true
  pairs:
    environment: dev
